version: '3.10'
services:
  simple-app:
    image: simple-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  migrate:
    image: migrate
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: db
      PGPORT: 5432
    depends_on:
      - db
volumes:
  postgres_data: